version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - set -euxo pipefail
      - echo "Running Unit Tests"
      - pip install -r requirements-dev.txt
      - pip install -r app/requirements.txt
      - make test
